title: "Belajar Corel"
author: "Farhan Cahyadi"
description: "Tutorial dan File Corel CDR"
permalink: /:title/
lang: "id"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", title: "Home", sidebaricon: home.svg}
    - {file: "archive.html", title: "", sidebaricon: home.svg}
  - {file: "tentang-blog.md", title: "Tentang Blog", sidebaricon: address-card}

comments:
   disqus_shortname: "belajarcorelweb"         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

future: true
